### ISSUE TITLE
webpack-dev-server will not run

### ISSUE THREAD

**Issue by d2rd** [learncodeacademy/react-js-tutorials#52]
webpack-dev-server will not run.  Following the video #3 for Redux I get the following error:

```
D2rdMac:4-redux d2rd$ npm run dev

> react-tutorials@0.0.0 dev /Users/d2rd/LambdaSchool/Tutorials/LearnCodeAcademy/react-js-tutorials/4-redux
> webpack-dev-server --content-base src --inline --hot

module.js:540
    throw err;
    ^

Error: Cannot find module 'webpack/bin/config-optimist'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/d2rd/LambdaSchool/Tutorials/LearnCodeAcademy/react-js-tutorials/4-redux/node_modules/webpack-dev-server/bin/webpack-dev-server.js:64:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-tutorials@0.0.0 dev: `webpack-dev-server --content-base src --inline --hot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-tutorials@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additionallogging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/d2rd/.npm/_logs/2018-05-05T23_33_02_290Z-debug.log
D2rdMac:4-redux d2rd$ npm install webpack
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta|| ^2.2.0-rc but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@1.12.2 requires a peer of webpack@^1.0.0 || ^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@1.16.5 requires a peer of webpack@>=1.3.0 <3 butnone is installed. You must install peer dependencies yourself.
npm WARN react-tutorials@0.0.0 No description
npm WARN react-tutorials@0.0.0 No repository field.

+ webpack@4.7.0
updated 1 package in 25.33s
D2rdMac:4-redux d2rd$
```

**Comment by MESepehr** [comment]
Hello, the below solution solved my problem
https://github.com/webpack/react-starter/issues/34
